spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 50MB

  datasource:
    url: jdbc:postgresql://localhost:5432/peek_pick_db
    driver-class-name: org.postgresql.Driver
    username: ppdbuser
    password: ppdbuser

  hikari:
    maximum-pool-size: 5
    minimum-idle: 2
    idle-timeout: 30000
    max-lifetime: 1800000
    connection-timeout: 2000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

  mvc:
    static-path-pattern: /uploads/**

logging:
  level:
    org.beep: INFO
    org.springframework.security: TRACE

notice:
  image:
    upload-dir: C:/peek-pick/uploads/notices/
    base-url: http://localhost:8080/uploads/
